---
title: "Merging all young and old Tracing data"
output: html_notebook
author: "Lukas and David"
date: 09-08-2019
---

## 1. Load packages, data and functions
### 1.1. Load packages

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(reshape2)
library(ggplot2)
library(Seurat)
library(scales)
library(hash)
library(stringr)

source(file = "Import10X-HelperFunctions.R")
```

### 1.2. Load datasets

```{r message=FALSE, warning=FALSE}
load("/media/ATLAS_ZMM_shared/David/ForStefanie/Lukas_Tracing/Not Imputed/Tracing.Rds")
load("/media/ATLAS_ZMM_shared/David/ForStefanie/Old_animals_tracing/Seurat2_Objects/Seurat_2_Female_old_AMI.Rds")
load("/media/ATLAS_ZMM_shared/David/ForStefanie/Old_animals_tracing/Seurat2_Objects/Seurat_2_Males_old_AMI.Rds")
```

### 1.3. Load function


## 2. Get GFP+ cells form datasets
```{r}
Females.GFP <- as.character(Females@meta.data$GFP)
names(Females.GFP) <- rownames(Females@meta.data)

Males.GFP <- as.character(Males@meta.data$GFP)
names(Males.GFP) <- rownames(Males@meta.data)

Young.GFP <- as.character(Tracing@meta.data$GFP)
names(Young.GFP) <- rownames(Tracing@meta.data)

# Remove Tam-Control sample from Young.GFP

Young.GFP <- Young.GFP[str_detect(names(Young.GFP), pattern = "Tam", negate = T)]

# Combine GFP.positives to large vector

GFP.cells <- factor(c(Males.GFP, Females.GFP, Young.GFP))

```

## 3. Read raw data

```{r}
######## Old data #############################

Paths = c("/media/Helios_scStorage/Lukas/103690/Mapped_to_EGFP/103690-001-004",
          "/media/Helios_scStorage/Lukas/103690/Mapped_to_EGFP/103690-001-005",
          "/media/Helios_scStorage/Lukas/103690/Mapped_to_EGFP/103690-001-006",
          "/media/Helios_scStorage/Lukas/103690/Mapped_to_EGFP/103690-001-007",
          "/media/Helios_scStorage/Lukas/103690/Mapped_to_EGFP/103690-001-008",
          "/media/Helios_scStorage/Lukas/103690/Mapped_to_EGFP/103690-001-009",
          "/media/Helios_scStorage/Lukas/103690/Mapped_to_EGFP/103690-001-010")
Paths_final = NULL
for(i in Paths){
  paths_new = paste0(i, "/outs/filtered_feature_bc_matrix")
  Paths_final = c(Paths_final, paths_new)
}
rm(i, paths_new, Paths)

Anno.old <- c("S_94", "S_97", "S_103", "S_102", "S_116", "S_113", "S_109")


# Additonal Sample information in table



############# Young data ######################

Paths.young <- c("/media/ATLAS_NGS_storage/Lukas/Tracer_Dec2018/103548_fastq/103548-001-001_cellrangerCount_CR3.0/001CR3/outs/filtered_feature_bc_matrix",
       "/media/ATLAS_NGS_storage/Lukas/Tracer_Dec2018/103548_fastq/103548-001-003_cellrangerCount_CR3.0/003CR3/outs/filtered_feature_bc_matrix",
       "/media/ATLAS_NGS_storage/Lukas/Tracer_Dec2018/103548_fastq/103548-001-005_cellrangerCount_CR3.0/005CR3/outs/filtered_feature_bc_matrix", 
       "/media/ATLAS_NGS_storage/Lukas/ShallowSCSeq_Tracer_GFP/Fastq_Combined/Tracer_D1_CR3_combined/outs/filtered_feature_bc_matrix",
       "/media/ATLAS_NGS_storage/Lukas/ShallowSCSeq_Tracer_GFP/Fastq_Combined/Tracer_Hom_CR3_combined/outs/filtered_feature_bc_matrix",
       "/media/ATLAS_NGS_storage/Lukas/ShallowSCSeq_Tracer_GFP/Fastq_Combined/Tracer_D3_CR3_combined/outs/filtered_feature_bc_matrix",
       "/media/ATLAS_NGS_storage/Lukas/ShallowSCSeq_Tracer_GFP/Fastq_Combined/Tracer_D7_CR3_combined/outs/filtered_feature_bc_matrix")

Anno.young <- c("d28", "d48", "d14", "d1", "Hom", "d3", "d7")

# Combine young and old

Paths <- c(Paths.young, Paths_final)
Anno <- c(Anno.young, Anno.old)

tbl = data.frame(Sample = factor(Anno, levels = Anno),
                 Sex = c("male","male","male","male","male","male","male","female", "female", "female", "female", "male", "male", "male"),
                 Age = c(rep("young",7),rep("old",7)),
                 AMI = c(Anno.young,"Hom", "3d", "7d", "14d", "Hom", "7d", "14d"),
                 orig.ident = Anno)


```

4. Merge Seurat Objects

```{r message=FALSE, warning=FALSE}
Tracing.old.young <- combineSeuratObjects(Paths, ids = Anno)
Tracing.old.young <- SubsetData(object = Tracing.old.young, cells.use = names(GFP.cells)) 
```


5. Add Meta data
```{r}
object<-Tracing.old.young
meta.data<-tbl

addTableToMetaData<- function(object, meta.data){
  
  meta.data %>% mutate_if(is.factor, as.character) -> meta.data
  rownames(meta.data)<-meta.data$Sample
  meta.data.assignments<- colnames(meta.data)[-1]

  for (variable in meta.data.assignments) {
    assign(variable, c())
  }

  for (barcode in colnames(object@data)) {
    
    tmp<-unlist(strsplit(barcode,split = "_"))
    if (length(tmp)>2) {
      tmp<-paste0(tmp[1],"_",tmp[2])
    } else {
      tmp<-tmp[1]
    }
    for (md in meta.data.assignments) {
      dummy<-get(md)
      currentValue<-as.character(meta.data[tmp,md])
      if (is.na(currentValue)) {
        print("Got NA from " ,md, " ", tmp)
      }
      dummy<-c(dummy,currentValue)
      assign(md,dummy)
    }
    
  }
  
  for (md in meta.data.assignments) {
    dummy<-get(md)
    names(dummy)<-object@cell.names
    object<-AddMetaData(object = object,metadata = dummy,col.name = md)
  }
  #table(condition)
  #names(condition)<-Tracing.old.young@cell.names
  #Tracing.old.young<-AddMetaData(object = Tracing.old.young,metadata = condition,col.name = "condition");rm(condition)
  return(object)
}


Tracing.old.young.final<-addTableToMetaData(Tracing.old.young, tbl)
save(Tracing.old.young.final, file = "/media/ATLAS_ZMM_shared/David/ForStefanie/TracingDataMerged.RData")

```

6. run preprocessing steps
```{r}
#divide by samplename 
Tracing.old.young.final<-SetAllIdent(Tracing.old.young.final,id = "orig.ident")
hvg<-c() #to save high variable genes
seurat.objects<-list() #list to dave Seurat objects
for (ident in names(table(Tracing.old.young.final@meta.data$orig.ident))){
    seuratObject<-SubsetData(Tracing.old.young.final, ident.use = ident)
    seuratObject<-NormalizeData(object = seuratObject)
    seuratObject<-FindVariableGenes(object = seuratObject, do.plot = FALSE)
    seuratObject<-ScaleData(object = seuratObject)

    hvg<-c(hvg,head(rownames(seuratObject@hvg.info), 1000)) #save variable genes
    seurat.objects<-c(seurat.objects,seuratObject)
  }
hvg2 <- names(which(table(hvg) > 1))#check if the variable genes are expressed in all sample
for (i in 1:length(seurat.objects)) {
  hv.combined <- hvg2[hvg2 %in% rownames(seurat.objects[[i]]@scale.data)]
}
  
Tracing.old.young.final.CCA<-RunMultiCCA(object.list = seurat.objects,genes.use = hv.combined)
cat("Merged Seurat object contains ", length(seuratObject@ident)," cells\n")
```

```{r}

Tracing.old.young.final.CCA <- FindVariableGenes(object = Tracing.old.young.final.CCA)
Tracing.old.young.final.CCA <- RunPCA(object = Tracing.old.young.final.CCA, features = VariableFeatures(object = Tracing.old.young.final.CCA), verbose = TRUE)
Tracing.old.young.final.CCA<-ProjectPCA(object = Tracing.old.young.final.CCA, do.print = FALSE)
PCHeatmap(object = Tracing.old.young.final.CCA, pc.use = 11:20, cells.use = 500, do.balanced = TRUE, label.columns = FALSE, use.full = FALSE)
Tracing.old.young.final.CCA <- FindClusters(object = Tracing.old.young.final.CCA, reduction.type = "pca", dims.use = 1:20, resolution = 0.6, print.output = 0, save.SNN = TRUE)
PrintFindClustersParams(object = Tracing.old.young.final.CCA)
Tracing.old.young.final.CCA <- RunTSNE(object = Tracing.old.young.final.CCA, dims.use = 1:20, do.label=TRUE, do.fast = TRUE)

save(Tracing.old.young.final, file = "/media/ATLAS_ZMM_shared/David/ForStefanie/TracingDataMerged.RData")

```



```{r}
Tracing.old.young.final.CCA<- SetAllIdent(object = Tracing.old.young.final.CCA, id = "res.0.6")
TSNEPlot(object = Tracing.old.young.final.CCA, label=T, pt.size = 0.1, do.return=TRUE)


Tracing.old.young.final.CCA<- SetAllIdent(object = Tracing.old.young.final.CCA, id = "AMI")
TSNEPlot(object = Tracing.old.young.final.CCA, label=T, pt.size = 0.1, do.return=TRUE, )

```

