---
title: "Circulating cells from Patient Cohorts (Seurat3)"
output: html_notebook
---

#1.) Unimputed Data (Both Runs Combined)
## 1.1) Import packages
```{r message=FALSE}
#load libraries
library(dplyr)
library(ggpubr)

require(scales)



source("/home/david/scRNA-SEQ-ZMM/Import10X-HelperFunctions_SeuratV3.R")
sink(file = "/media/ATLAS_NGS_storage/Wesley/AnalysisDavid-2019-Seurat3/Unimputed/SamplesForSubmission/Wesley-PatientData-circulatingCells.rmd.log", append = TRUE, split = TRUE)
```


## 1.2) Define static parameters
```{r}
#Static Parameters 
Paths <- c(
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy_Run2/103588-001-003/outs/filtered_feature_bc_matrix/",
  
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy_Run2/103588-001-004/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy_Run2/103588-001-005/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy_Run2/103588-001-006/outs/filtered_feature_bc_matrix/",
  
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy_Run2/103588-001-007/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy_Run2/103588-001-008/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy_Run2/103588-001-009/outs/filtered_feature_bc_matrix/",
  
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy_Run2/103588-001-012/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy/103305-001-001/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy/103305-001-002/outs/filtered_feature_bc_matrix/",

  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy/103305-001-003/outs/filtered_feature_bc_matrix/",
  
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy/103305-001-004/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy/103305-001-005/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy/103305-001-006/outs/filtered_feature_bc_matrix/",
  
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy/103305-001-007/outs/filtered_feature_bc_matrix/",
  "/media/ATLAS_NGS_storage/Wesley/scRNA-SEQ_circulating-CD31+_HeartFailure_Healthy/103305-001-008/outs/filtered_feature_bc_matrix/")


Samplenames <- c("HF-2.1",
"HF-2.2","HF-2.3","HF-2.4",
"HC2.1","HC2.2","HC2.3",
"HCY2.1","HCY1.1","HCY1.2",
"HCY1.3","HCY1.4","HF1.1",
"HF1.2","HF1.3","HF1.4")
```


## 1.3) import and combine the raw cellranger counts with CCA
```{r}
SeuratObjectList <- list()
for (i in 1:length(Paths)) {
  SeuratObjectList[[i]]<-Importer(pathway = Paths[i],id = Samplenames[i])
}
```
```{r}
for (i in 1:length(SeuratObjectList)) {
  print(i)
  tmp<-SeuratObjectList[[i]]
  tmp<-ScaleData(object = tmp)
  tmp<-RunPCA(object = tmp, verbose = FALSE, ndims.print = 0)
  DimHeatmap(object = tmp, dims = 1:15, )
  gg<-ElbowPlot(tmp, ndims = 10) + labs(title=as.character(i))
  print(gg)
}
```


```{r}
Sana.anchors <- FindIntegrationAnchors(object.list = SeuratObjectList, dims = 1:10, k.filter = 150)
Sana.combined <- IntegrateData(anchorset = CD31.anchors, dims = 1:10)


```


```{r}
DefaultAssay(object = CD31.combined) <- "integrated"
DefaultAssay(object = CD31.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
CD31.combined <- ScaleData(object = CD31.combined, verbose = FALSE)
CD31.combined <- RunPCA(object = CD31.combined, npcs = 30, verbose = FALSE)
# t-SNE and Clustering
#CD31.combined <- RunUMAP(object = CD31.combined, reduction = "pca", dims = 1:20)
CD31.combined <- RunTSNE(object = CD31.combined, reduction = "pca", dims = 1:20)
CD31.combined <- FindNeighbors(object = CD31.combined, reduction = "pca", dims = 1:20)
CD31.combined <- FindClusters(CD31.combined, resolution = 0.5)
```

```{r}
CD31.combined<-readRDS("/media/ATLAS_NGS_storage/Wesley/AnalysisDavid-2019-Seurat3/Unimputed/SamplesForSubmission/CD31_SamplesForSubmission_Seurat3_Sep2019.Rds")
saveRDS(CD31.combined,"/media/ATLAS_NGS_storage/Wesley/AnalysisDavid-2019-Seurat3/Unimputed/SamplesForSubmission/CD31_SamplesForSubmission_Seurat3_Sep2019.Rds")


  
```

#add condition meta data
```{r}
condition<-c()
for (ident in CD31.combined@meta.data$orig.ident) {
  tmp<- substr(ident, 1,2)
  condition<-c(condition,tmp)
}
names(condition)<-names(CD31.combined@active.ident)
CD31.combined$condition<-condition
```

```{r}
table(condition)
table(CD31.combined@meta.data$orig.ident)
table(CD31.combined$condition)
CD31.combined$s
```

#plot TSNE's
```{r}
  DimPlot(object = CD31.combined, label=T, pt.size = 0.1, do.return=TRUE)
  DimPlot(object = CD31.combined, group.by = "orig.ident", pt.size = 0.001, split.by = "condition")
  DimPlot(object = CD31.combined, group.by = "seurat_clusters", pt.size = 0.001, split.by = "orig.ident")

```

```{r}
DimHeatmap(CD31.combined, dims = 1:5, nfeatures = 50, balanced = TRUE, reduction = "pca", fast = TRUE)

CD31.combined=BuildClusterTree(CD31.combined,reorder = TRUE)
PlotClusterTree(object = CD31.combined)

```

##1.6) Barplot of cell per cluster
```{r fig.height=10, fig.width=15}
# Counting celltypes in timepoints
V<- CD31.combined@meta.data
orig.ident.ordered<-str_sort(unique(CD31.combined@meta.data$orig.ident),numeric = TRUE)
V$orig.ident<-factor(V$orig.ident,levels = orig.ident.ordered)
table(V$seurat_clusters)
V$seurat_clusters<-factor(V$seurat_clusters,levels = c(0:13))

Summary.Celltypes <- V %>% count(orig.ident,seurat_clusters,.drop = FALSE) %>% group_by(orig.ident) %>%
  mutate(freq = n /sum(n)) %>% complete(seurat_clusters,fill = list(n=0,freq=0))

Summary.Celltypes$seurat_clusters <- factor(Summary.Celltypes$seurat_clusters)
condition<-c()
for (ident in Summary.Celltypes$orig.ident) {
  tmp<- substr(ident, 1,2)
  condition<-c(condition,tmp)
}
Summary.Celltypes$condition<-condition

#svg(filename = "/media/ATLAS_NGS_storage/Wesley/AnalysisDavid-2019/Unimputed/allCells/Barplot-CellsperClusterPerSample.svg",width = 15, height = 10)
ggplot(Summary.Celltypes, aes(x=orig.ident, y= freq, fill= condition))+
  geom_col(width = 0.9, color = "black")+
  facet_wrap(~condition, nrow = 4, scales = "free")+
  scale_y_continuous(name = "Percent per timepoint", labels = scales::percent_format())+
  theme(panel.background = element_blank(), axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust= 1, size = 8))
```




```{r}
# Annotation markers

B.Cell.Annotationmarkers <- c("CD79A", "CD79B", "MS4A1", "CD19", "CD72", "CD40", "CD22")
CD4.T.Cell.Annotationmarkers <- c("LDHB", "CD3D", "CD3E", "CD27", "CD2", "CD3G", "CD7", "CD69", "CD4", "CTLA4", "LCK", "CD28")
CD.8.T.Cell.Annotationmarkers <- c("CD8A", "CD3D", "CD8B", "CD3E", "CD2", "CD160", "CD247", "CD320")
CD14.Monocytes.Annotationmarkers <- c("FCN1", "S100A8", "S100A9", "S100A12", "FCGR1A", "TREM1", "LGALS1", "CD14", "CST3", "FTL")
Dendritic.Cell.Annotationmarkers <- c("CLEC10A", "CLEC4C", "CLIC2", "PKIB", "GAS6", "SERPINF2", "LILRA4", "ENHO", "PON2", "PHLDA2")
FCGR3A.Monocyte.Annotationmarkers <- c("HES4", "CDKN1C", "MS4A7", "FCGR3A", "HMOX1")
General.Monocytes.Annotationmarkers <- c("FCN1", "S100A8", "S100A9", "S100A12",  "LGALS1", "CD14", "CDKN1C", "MS4A7", "FCGR3A", "HMOX1")
Megakaryocyte.Annotationmarkers <- c("ITGA2B", "PF4", "ITGB3")
NK.cell.Annotationmarkers <- c("FGFBP2", "XCL2", "SPON2", "KLRC1",  "KIR3DL1", "KLRD1")
Neutrophil.Annotation.markers <- c("ELANE", "FUT4")
Collective.markers.annotation <- c("ELANE", "FUT4", "FGFBP2", "XCL2", "SPON2","FCGR3A", "KLRC1",  "KIR3DL1", "KLRD1", "ITGA2B", "ITGB3", "CD79A", "CD79B", "MS4A1", "CD19", "CD72", "CD40", "CD22", "CD8A", "CD8B", "LDHB", "CD3D", "CD3E", "CD27", "CD2", "CD3G", "HMOX1", "CDKN1C", "MS4A7",   "FCN1", "S100A8", "S100A9", "S100A12",  "LGALS1", "CD14")


# Visualize expression of markers by cluster (set ident to res.XXXX)

DotPlot(object = CD31.combined, features = Collective.markers.annotation, assay = "RNA", cols.use = c("gray99", "blue"), plot.legend = T, x.lab.rot = 45)
```

#subset Monocytes
```{r}
Idents(CD31.combined)<-"seurat_clusters" 

CD31.combined.Monocytes <- WhichCells(object = CD31.combined, idents = c(1,2))

CD31.combined.Monocytes <- subset(x=CD31.combined, idents = c(1,2,3,5,6,7,8,12,13,15,17,18))

saveRDS(CD31.combined.Monocytes,"/media/ATLAS_NGS_storage/Wesley/AnalysisDavid-2019-Seurat3/Unimputed/SamplesForSubmission/CD31_SamplesForSubmission_Monocytes_Seurat3_Sep2019.Rds")
CD31.combined.Monocytes<-readRDS("/media/ATLAS_NGS_storage/Wesley/AnalysisDavid-2019-Seurat3/Unimputed/SamplesForSubmission/CD31_SamplesForSubmission_Monocytes_Seurat3_Sep2019.Rds")

table(CD31.combined.Monocytes@meta.data$seurat_clusters)
CD31.combined.Monocytes<-FindVariableFeatures(object = CD31.combined.Monocytes, assay = "RNA")
CD31.combined.Monocytes <- RunPCA(object = CD31.combined.Monocytes, npcs = 20, verbose = TRUE)
# t-SNE and Clustering
#CD31.combined.Monocytes <- RunUMAP(object = CD31.combined.Monocytes, reduction = "pca", dims = 1:20)
CD31.combined.Monocytes <- RunTSNE(object = CD31.combined.Monocytes, reduction = "pca", dims = 1:20)
CD31.combined.Monocytes <- FindNeighbors(object = CD31.combined.Monocytes, reduction = "pca", dims = 1:20)
CD31.combined.Monocytes <- FindClusters(CD31.combined.Monocytes, resolution = 0.5)
```



```{r}
DimPlot(object = CD31.combined.Monocytes, label=T, pt.size = 0.1, do.return=TRUE)
DimPlot(object = CD31.combined.Monocytes, label=T, pt.size = 0.1, do.return=TRUE, split.by = "condition")

FeaturePlot(CD31.combined.Monocytes, features = c("CD14", "FCGR3A"))
CD31.combined.Monocytes<-BuildClusterTree(CD31.combined.Monocytes)
PlotClusterTree(CD31.combined.Monocytes)
```


```{r}
CD31.combined.Monocytes.markers<-FindAllMarkers(CD31.combined.Monocytes,assay = "RNA", only.pos = TRUE)

#dotplot of top10 markers
tmp <- CD31.combined.Monocytes.markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_logFC)
DotPlot(CD31.combined.Monocytes, assay = "RNA",features = c("S100A8"))
DotPlot(CD31.combined.Monocytes, assay = "RNA",features = unique(as.character(tmp$gene))) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) 

#Subset T-Cells
#reclusters T-cells

```


##1.6) Barplot of cell per cluster
```{r fig.height=10, fig.width=15}
# Counting celltypes in timepoints
library(tidyr)
library(stringr)
library(dplyr)
library(ggplot2)
library(scales)
library(Seurat)
V<- CD31.combined.Monocytes@meta.data
orig.ident.ordered<-str_sort(unique(CD31.combined.Monocytes@meta.data$orig.ident),numeric = TRUE)
V$orig.ident<-factor(V$orig.ident,levels = orig.ident.ordered)
table(V$seurat_clusters)
V$seurat_clusters<-factor(V$seurat_clusters,levels = c(0:13))

Summary.Celltypes <- V %>% count(orig.ident,seurat_clusters,.drop = FALSE) %>% group_by(orig.ident) %>%
  mutate(freq = n /sum(n)) %>% complete(seurat_clusters,fill = list(n=0,freq=0))

Summary.Celltypes$seurat_clusters <- factor(Summary.Celltypes$seurat_clusters)
condition<-c()
for (ident in Summary.Celltypes$orig.ident) {
  tmp<- substr(ident, 1,2)
  condition<-c(condition,tmp)
}
Summary.Celltypes$condition<-condition

#svg(filename = "/media/ATLAS_NGS_storage/Wesley/AnalysisDavid-2019/Unimputed/allCells/Barplot-CellsperClusterPerSample.svg",width = 15, height = 10)
ggplot(Summary.Celltypes, aes(x=orig.ident, y= freq, fill= condition))+
  geom_col(width = 0.9, color = "black")+
  facet_wrap(~seurat_clusters, nrow = 4, scales = "free")+
  scale_y_continuous(name = "Percent per timepoint", labels = scales::percent_format())+
  theme(panel.background = element_blank(), axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust= 1, size = 8))


ggplot(Summary.Celltypes, aes(x=seurat_clusters, y= freq, fill= condition))+
  geom_col(width = 0.9, color = "black")+
  facet_wrap(~orig.ident, nrow = 4, scales = "free")+
  scale_y_continuous(name = "Percent per timepoint", labels = scales::percent_format())+
  theme(panel.background = element_blank(), axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust= 1, size = 8))
```


#subset T-Cells
TODO: 































#run Slingshot
```{r}
library(monocle)
library(slingshot)
library(SummarizedExperiment)
library(ggbeeswarm)
library(ggplot2)
library(ggthemes)

#generate SingleCellExperiments Object
CD31.combined.Monocytes.sce <- as.SingleCellExperiment(CD31.combined.Monocytes)
colData(CD31.combined.Monocytes.sce)$seurat_clusters <- as.character(CD31.combined.Monocytes$seurat_clusters)  # go from factor to character
colData(CD31.combined.Monocytes.sce)$orig.ident <- as.character(CD31.combined.Monocytes$orig.ident)  # go from factor to character
colData(CD31.combined.Monocytes.sce)$condition <- as.character(CD31.combined.Monocytes$condition)  # go from factor to character

CD31.combined.Monocytes.sce <- slingshot(CD31.combined.Monocytes.sce, clusterLabels = "seurat_clusters")
colors <- rainbow(50, alpha = 1)

#do plots
plot(reducedDims(CD31.combined.Monocytes.sce)$PCA, col = colors[cut(CD31.combined.Monocytes.sce$slingPseudotime_1,breaks=10)], pch=16, asp = 1)
lines(SlingshotDataSet(CD31.combined.Monocytes.sce))

# Plot Slingshot pseudotime vs cell stage. 
ggplot(as.data.frame(colData(CircResBothCohortsMonocytes.final.sce)), aes(x = slingPseudotime_1, y = Monocyte.Annotations, 
                                                                                      colour = Monocyte.Annotations)) +
  geom_quasirandom(groupOnX = FALSE) +
  scale_color_tableau() + theme_classic() +
  xlab("Slingshot pseudotime") + ylab("Timepoint") +
  ggtitle("Cells ordered by Slingshot pseudotime")

```

